name: Build Qt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: "${{ github.workspace }}/build"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: PWD
        run: |
          pwd
          echo ${{ github.workspace }}/qt5

      - name: Make builddir 
        run: mkdir ${{ env.BUILD_DIR }}

      - name: Update submodules 
        run: git submodule update --init --recursive

      - name: Configure Qt
        working-directory: ${{ env.BUILD_DIR }}
        run: ${{ github.workspace }}/qt5/configure -opensource -confirm-license -nomake examples -nomake tests -release -platform linux-clang-libc++
