name: Build Qt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update submodules 
        run: git submodule update --init --recursive

      - name: Make builddir 
        run: mkdir ${{ env.GITHUB_WORKSPACE }}/build

      - name: Configure Qt
        working-directory: ${{ env.GITHUB_WORKSPACE }}/build
        run: ${{ env.GITHUB_WORKSPACE }}/qt5/configure -opensource -confirm-license -nomake examples -nomake tests -release -platform linux-clang-libc++
