
name: CI

on:
  push:
    branches: [ 5.15.2 ]
  pull_request:
    branches: [ 5.15.2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update submodules 
        run: git submodule update --init --recursive
