
# This is a basic workflow that is manually triggered

name: Release Qt

on:
  workflow_dispatch:
    inputs:
      archive_name:
        description: 'Archive name'
        default: 'qt-everywhere-src-5.15.2'
        required: true

jobs:
  make_archive:
    runs-on: ubuntu-latest
    env:
      WORK_DIR: "${{ github.workspace }}/.."

    steps:
      - uses: actions/checkout@v2

      - name: Get git-archive-all
        working-directory: ${{ env.WORK_DIR }}
        run: |
          git clone https://github.com/Kentzo/git-archive-all.git
          cd git-archive-all
          git checkout 1.23.0

      - name: Make archive 
        run: ../git-archive-all/git_archive_all.py -v --force-submodules ${{ github.event.inputs.archive_name }}.tar.xz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.archive_name }}.tar.xz
          path: ${{ github.event.inputs.archive_name }}.tar.xz
